// *****************************************************************************
// Copyright (C) 2024 NukeHub and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0
// *****************************************************************************

/**
 * XML Generation Service
 * 
 * Frontend service for generating OpenMC XML files from the simulation state.
 * This is a placeholder for Phase 1 implementation.
 * 
 * @module openmc-studio/browser
 */

import { injectable, inject } from '@theia/core/shared/inversify';
import { MessageService } from '@theia/core/lib/common/message-service';

import { OpenMCState } from '../../common/openmc-state-schema';
import {
    XMLGenerationRequest,
    XMLGenerationResult,
    OpenMCStudioBackendService
} from '../../common/openmc-studio-protocol';

@injectable()
export class OpenMCXMLGenerationService {
    
    @inject(MessageService)
    protected readonly messageService: MessageService;
    
    @inject(OpenMCStudioBackendService)
    protected readonly backendService: OpenMCStudioBackendService;

    /**
     * Generate XML files from the current state.
     */
    async generateXML(
        state: OpenMCState,
        outputDirectory: string,
        options: {
            geometry?: boolean;
            materials?: boolean;
            settings?: boolean;
            tallies?: boolean;
            plots?: boolean;
            overwrite?: boolean;
        } = {}
    ): Promise<XMLGenerationResult> {
        const request: XMLGenerationRequest = {
            state,
            outputDirectory,
            files: {
                geometry: options.geometry ?? true,
                materials: options.materials ?? true,
                settings: options.settings ?? true,
                tallies: options.tallies ?? true,
                plots: options.plots ?? false
            },
            overwrite: options.overwrite ?? true,
            headerComment: `Generated by OpenMC Studio - ${new Date().toISOString()}`
        };

        try {
            const result = await this.backendService.generateXML(request);
            
            if (result.success) {
                this.messageService.info(
                    `Generated ${result.generatedFiles.length} XML files`
                );
            } else {
                this.messageService.error(
                    `XML generation failed: ${result.error}`
                );
            }
            
            return result;
        } catch (error) {
            const msg = error instanceof Error ? error.message : String(error);
            this.messageService.error(`XML generation error: ${msg}`);
            
            return {
                success: false,
                generatedFiles: [],
                error: msg
            };
        }
    }
}
