// *****************************************************************************
// Copyright (C) 2024 NukeHub and others.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
// SPDX-License-Identifier: BSD-2-Clause
// *****************************************************************************

/**
 * XML Generation Service
 * 
 * Frontend service for generating OpenMC XML files from the simulation state.
 * 
 * @module openmc-studio/browser
 */

import { injectable, inject } from '@theia/core/shared/inversify';
import { MessageService } from '@theia/core/lib/common/message-service';

import { OpenMCState } from '../../common/openmc-state-schema';
import {
    XMLGenerationRequest,
    XMLGenerationResult,
    XMLImportRequest,
    XMLImportResult,
    OpenMCStudioBackendService
} from '../../common/openmc-studio-protocol';

export interface XMLGenerationOptions {
    geometry?: boolean;
    materials?: boolean;
    settings?: boolean;
    tallies?: boolean;
    plots?: boolean;
    overwrite?: boolean;
}

@injectable()
export class OpenMCXMLGenerationService {
    
    @inject(MessageService)
    protected readonly messageService: MessageService;
    
    @inject(OpenMCStudioBackendService)
    protected readonly backendService: OpenMCStudioBackendService;

    /**
     * Generate XML files from the current state using a request object.
     */
    async generateXML(request: XMLGenerationRequest): Promise<XMLGenerationResult>;
    
    /**
     * Generate XML files from the current state using individual parameters.
     */
    async generateXML(
        state: OpenMCState,
        outputDirectory: string,
        options?: XMLGenerationOptions
    ): Promise<XMLGenerationResult>;
    
    async generateXML(
        arg1: OpenMCState | XMLGenerationRequest,
        outputDirectory?: string,
        options?: XMLGenerationOptions
    ): Promise<XMLGenerationResult> {
        let request: XMLGenerationRequest;
        
        if (typeof arg1 === 'object' && 'state' in arg1 && 'outputDirectory' in arg1) {
            // Called with XMLGenerationRequest object
            request = arg1 as XMLGenerationRequest;
        } else {
            // Called with separate parameters
            const state = arg1 as OpenMCState;
            request = {
                state,
                outputDirectory: outputDirectory!,
                files: {
                    geometry: options?.geometry ?? true,
                    materials: options?.materials ?? true,
                    settings: options?.settings ?? true,
                    tallies: options?.tallies ?? true,
                    plots: options?.plots ?? false
                },
                overwrite: options?.overwrite ?? true,
                headerComment: `Generated by OpenMC Studio - ${new Date().toISOString()}`
            };
        }

        try {
            const result = await this.backendService.generateXML(request);
            
            if (result.success) {
                this.messageService.info(
                    `Generated ${result.generatedFiles.length} XML files`
                );
            } else {
                this.messageService.error(
                    `XML generation failed: ${result.error}`
                );
            }
            
            return result;
        } catch (error) {
            const msg = error instanceof Error ? error.message : String(error);
            this.messageService.error(`XML generation error: ${msg}`);
            
            return {
                success: false,
                generatedFiles: [],
                error: msg
            };
        }
    }

    /**
     * Import XML files into the simulation state.
     */
    async importXML(request: XMLImportRequest): Promise<XMLImportResult> {
        try {
            const result = await this.backendService.importXML(request);
            
            if (result.success) {
                this.messageService.info(
                    `Imported XML files with ${result.warnings?.length || 0} warnings`
                );
            } else {
                this.messageService.error(
                    `XML import failed: ${result.errors?.join(', ')}`
                );
            }
            
            return result;
        } catch (error) {
            const msg = error instanceof Error ? error.message : String(error);
            this.messageService.error(`XML import error: ${msg}`);
            
            return {
                success: false,
                state: undefined,
                errors: [msg],
                warnings: []
            };
        }
    }
}
