#!/usr/bin/env python3
"""
OpenMC Criticality (k-eff) Search Runner

Drives openmc.search_for_keff to find the value of a single model parameter
that produces a target k-effective. It is designed to be called from the
OpenMC Studio optimization widget ('Criticality Search' mode).

The searchable parameter uses the IDE's optimization parameter vocabulary
(the same descriptor parameter sweeps use):
    <materialName>.density          material density
    <materialName>.temperature      material temperature
    <materialName>.<nuclideName>    nuclide fraction (others renormalized)
    settings.particles|batches|inactive|seed
    geometry.<cellName>.temperature

The working directory must contain the base model XML files (generated by the
backend from the current IDE state). Per iteration, the model_builder shim
clones the base model, applies the guessed parameter value, and hands it to
search_for_keff, which runs it via Model.run in the working directory.

Usage:
    python run_keff_search.py <working_directory> --parameter <path> [options]

Options:
    --parameter PATH     Parameter to search (required; see vocabulary above)
    --target K           Target k-effective (default 1.0)
    --initial-guess X    Initial guess (secant method; ignored when --bracket is set)
    --bracket LO,HI      Bracketing interval (enables bracketed methods)
    --method M           Bracketed method: brentq | brenth | ridder | bisect (default bisect)
    --tol T              Solver tolerance (default 1e-8; search.py requires an explicit tol)
"""

import argparse
import copy
import json
import os
import sys
import traceback
from pathlib import Path


def log_progress(message: str):
    """Print progress message to stderr for real-time communication.

    Args:
        message: Progress message to emit.
    """
    print(f"{message}", file=sys.stderr, flush=True)


def _json_safe(obj):
    """Fallback JSON encoder for numpy scalars/arrays (without importing numpy).

    Args:
        obj: Object that failed default JSON serialization.

    Returns:
        A JSON-serializable equivalent.
    """
    if hasattr(obj, "item"):
        return obj.item()
    if hasattr(obj, "tolist"):
        return obj.tolist()
    return str(obj)


def _element_symbol(name):
    """Extract the element symbol from a nuclide name ('U235' → 'u', 'Am242_m1' → 'am', 'O16' → 'o').

    Args:
        name: Nuclide name.

    Returns:
        Lowercase element symbol.
    """
    import re

    match = re.match(r"^([A-Za-z]+)", name)
    return match.group(1).lower() if match else name.lower()


def apply_search_parameter(model, param_path, value):
    """Apply a parameter value to an openmc.Model using the IDE's optimization
    parameter vocabulary (mirrors src/common/parameter-paths.ts semantics).

    Args:
        model: openmc.Model to modify (mutated in place).
        param_path: Dot-separated parameter path (e.g. 'water.density').
        value: Value to assign.

    Raises:
        ValueError: If the path does not resolve against the model.
    """
    parts = param_path.split(".")
    if len(parts) < 2:
        raise ValueError(f"Invalid parameter path: {param_path}")

    prefix, target_field = parts[0], ".".join(parts[1:])

    if prefix == "settings":
        run_settings = model.settings
        if target_field in ("particles", "batches", "inactive", "seed"):
            setattr(
                run_settings,
                target_field,
                max(1 if target_field != "inactive" else 0, round(value)),
            )
            return
        raise ValueError(f"Unsupported settings parameter: {param_path}")

    if prefix == "geometry":
        cell_parts = target_field.split(".")
        if len(cell_parts) == 2 and cell_parts[1] == "temperature":
            cell_name = cell_parts[0].lower()
            for cell in model.geometry.get_all_cells().values():
                if (cell.name or "").lower() == cell_name:
                    cell.temperature = value
                    return
            raise ValueError(f"Cell not found for parameter: {param_path}")
        raise ValueError(f"Unsupported geometry parameter: {param_path}")

    # Material parameter: <materialName>.<density|temperature|nuclideName>
    material = None
    for mat in model.materials:
        if (mat.name or "").lower() == prefix.lower():
            material = mat
            break
    if material is None:
        raise ValueError(f"Material not found for parameter: {param_path}")

    prop = target_field.lower()
    if prop == "density":
        material.set_density(material.density_units, value)
        return
    if prop == "temperature":
        material.temperature = value
        return

    # Nuclide fraction with ELEMENT-SCOPED renormalization (e.g. enriching
    # U235 scales U238 only — compound stoichiometry like O16 is preserved).
    # Mirrors setNuclideFraction in src/common/parameter-paths.ts.
    target = None
    for nuc in material.nuclides:
        if nuc.name.lower() == prop:
            target = nuc
            break
    if target is None:
        raise ValueError(f"Nuclide not found for parameter: {param_path}")

    target_element = _element_symbol(target.name)
    siblings = [
        nuc
        for nuc in material.nuclides
        if nuc is not target
        and _element_symbol(nuc.name) == target_element
        and nuc.percent_type == target.percent_type
    ]

    if not siblings:
        target.percent = value
        return

    element_total = target.percent + sum(nuc.percent for nuc in siblings)
    remaining = element_total - value
    sibling_total = sum(nuc.percent for nuc in siblings)
    target.percent = value
    if sibling_total > 0:
        for nuc in siblings:
            nuc.percent = (nuc.percent / sibling_total) * remaining
    else:
        for nuc in siblings:
            nuc.percent = remaining / len(siblings)


def run_search(args):
    """Run the criticality search.

    Loads the base model from the working directory XML, wraps it in a
    model_builder shim for search_for_keff, and runs the root finder.

    Args:
        args: Parsed command-line arguments.

    Returns:
        Dictionary with success flag, converged value, final k-eff, per-iteration
        history, method used, target, and the searched parameter.

    Raises:
        ValueError: If neither initial guess nor bracket is provided, or the
            bracket is invalid.
    """
    import openmc
    from openmc.search import search_for_keff

    working_dir = Path(args.working_directory).absolute()
    os.chdir(working_dir)

    if not (working_dir / "settings.xml").exists():
        raise FileNotFoundError(
            f"settings.xml not found in {working_dir} — generate XML inputs first"
        )

    # Parse and validate the search interval
    bracket = None
    if args.bracket:
        values = [float(v.strip()) for v in args.bracket.split(",")]
        if len(values) != 2 or values[0] >= values[1]:
            raise ValueError(
                f"Invalid bracket '{args.bracket}': expected 'low,high' with low < high"
            )
        bracket = values
    if bracket is None and args.initial_guess is None:
        raise ValueError("Either --initial-guess or --bracket must be provided")

    method = args.method if bracket is not None else "secant"

    log_progress(f"Loading base model from {working_dir}")
    materials = openmc.Materials.from_xml("materials.xml")
    geometry = openmc.Geometry.from_xml("geometry.xml", materials)
    settings = openmc.Settings.from_xml("settings.xml")
    base_model = openmc.Model(geometry, materials, settings)

    parameter = args.parameter

    def model_builder(guess):
        """Build a model copy with the searched parameter set to `guess`."""
        model = copy.deepcopy(base_model)
        apply_search_parameter(model, parameter, float(guess))
        return model

    log_progress(
        f"Searching {parameter} for k-eff = {args.target} "
        f"({method}, {'bracket ' + str(bracket) if bracket else f'initial guess {args.initial_guess}'}, tol={args.tol})"
    )

    # search_for_keff requires an explicit tol in this OpenMC version
    # (search.py:138 checks tol against Real without none_ok)
    zero_value, guesses, results = search_for_keff(
        model_builder,
        initial_guess=args.initial_guess,
        target=args.target,
        bracket=bracket,
        tol=args.tol,
        bracketed_method=args.method,
        print_iterations=True,
        run_args={"cwd": str(working_dir)},
    )

    iterations = []
    for i, (guess, keff) in enumerate(zip(guesses, results, strict=True), 1):
        iterations.append(
            {
                "iteration": i,
                "guess": float(guess),
                "keff": float(getattr(keff, "n", keff)),
                "keffStd": float(getattr(keff, "s", 0.0)),
            }
        )

    final = iterations[-1] if iterations else {"keff": None, "keffStd": None}
    log_progress(f"Converged: {parameter} = {zero_value:.6g} (final k-eff {final['keff']})")

    return {
        "success": True,
        "convergedValue": float(zero_value),
        "finalKeff": final["keff"],
        "finalKeffStd": final["keffStd"],
        "iterations": iterations,
        "method": method,
        "target": args.target,
        "parameter": parameter,
    }


def main():
    """Main entry point for CLI usage.

    Parses arguments, runs the criticality search, and prints the result as
    JSON to stdout (also written to keff_search_result.json).
    """
    parser = argparse.ArgumentParser(
        description="Find the parameter value producing a target k-effective",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python run_keff_search.py /path/to/sim --parameter water.density --bracket 0.5,1.5 --method brentq
    python run_keff_search.py /path/to/sim --parameter fuel.U235 --initial-guess 0.05 --target 1.0
        """,
    )

    parser.add_argument("working_directory", help="Directory containing the base model XML files")
    parser.add_argument(
        "--parameter", required=True, help="Parameter path to search (e.g. water.density)"
    )
    parser.add_argument(
        "--target", type=float, default=1.0, help="Target k-effective (default 1.0)"
    )
    parser.add_argument("--initial-guess", type=float, help="Initial guess (secant method)")
    parser.add_argument(
        "--bracket", help="Bracketing interval as 'low,high' (enables bracketed methods)"
    )
    parser.add_argument(
        "--method",
        default="bisect",
        choices=["brentq", "brenth", "ridder", "bisect"],
        help="Bracketed root-finding method (only used with --bracket)",
    )
    parser.add_argument("--tol", type=float, default=1e-8, help="Solver tolerance (default 1e-8)")

    args = parser.parse_args()

    try:
        result = run_search(args)
        result_path = Path(args.working_directory).absolute() / "keff_search_result.json"
        result_path.write_text(json.dumps(result, indent=2, default=_json_safe))
        print(json.dumps(result, default=_json_safe))
        return 0
    except Exception as e:
        log_progress(f"FAILED: {e}")
        traceback.print_exc(file=sys.stderr)
        error_result = {"success": False, "error": str(e)}
        print(json.dumps(error_result))
        return 1


if __name__ == "__main__":
    sys.exit(main())
