// *****************************************************************************
// Copyright (C) 2024 NukeHub and others.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0
// *****************************************************************************

export const blueLightTheme = {
    $schema: 'vscode://schemas/color-theme',
    name: 'Blue Light',
    type: 'light',
    colors: {
        'focusBorder': '#0288d1',
        'foreground': '#2c3e50',
        'descriptionForeground': '#5a6c7d',
        'errorForeground': '#d13b3b',

        'button.background': '#0288d1',
        'button.hoverBackground': '#039be5',
        'button.foreground': '#ffffff',
        'button.secondaryBackground': '#e4e4e4',
        'button.secondaryHoverBackground': '#d4d4d4',
        'button.secondaryForeground': '#2c3e50',

        'textLink.foreground': '#0288d1',
        'textLink.activeForeground': '#039be5',

        'activityBar.background': '#ebf1f5',
        'activityBar.foreground': '#424242',
        'activityBar.activeBorder': '#0288d1',
        'activityBar.border': '#ccd3d9',
        'activityBarBadge.background': '#0288d1',
        'activityBarBadge.foreground': '#ffffff',

        'sideBar.background': '#ebf1f5',
        'sideBar.foreground': '#424242',
        'sideBarTitle.foreground': '#24292f',
        'sideBar.border': '#ccd3d9',
        'sideBarSectionHeader.background': '#e1e8ed',
        'sideBarSectionHeader.foreground': '#24292f',
        'sideBarSectionHeader.border': '#ccd3d9',

        'statusBar.background': '#ebf1f5',
        'statusBar.foreground': '#424242',
        'statusBar.border': '#ccd3d9',
        'statusBar.noFolderBackground': '#ebf1f5',
        'statusBarItem.remoteBackground': '#546e7a',
        'statusBarItem.remoteForeground': '#ffffff',
        'statusBarItem.hoverBackground': '#ccd3d9',
        'statusBarItem.activeBackground': '#d0d7de',

        'titleBar.activeBackground': '#ebf1f5',
        'titleBar.activeForeground': '#2c3e50',
        'titleBar.border': '#ccd3d9',
        'titleBar.inactiveBackground': '#ebf1f5',
        'titleBar.inactiveForeground': '#6c757d',

        'menubar.selectionBackground': '#e1e4e8',
        'menubar.selectionForeground': '#2c3e50',
        'menubar.selectionBorder': '#e1e4e8',
        'menu.background': '#ffffff',
        'menu.foreground': '#2c3e50',
        'menu.selectionBackground': '#e1e4e8',
        'menu.selectionForeground': '#2c3e50',
        'menu.selectionBorder': '#e1e4e8',
        'menu.separatorBackground': '#e1e4e8',

        'list.activeSelectionBackground': '#e0e0e0',
        'list.activeSelectionForeground': '#2c3e50',
        'list.inactiveSelectionBackground': '#ebf1f5',
        'list.inactiveSelectionForeground': '#2c3e50',
        'list.hoverBackground': '#e1e8ed',
        'list.hoverForeground': '#2c3e50',
        'list.highlightForeground': '#0288d1',
        'list.focusBackground': '#e1e8ed',
        'list.focusForeground': '#2c3e50',
        'list.focusOutline': '#0288d1',

        'input.background': '#ffffff',
        'input.foreground': '#2c3e50',
        'input.border': '#ccd3d9',
        'input.placeholderForeground': '#8c959f',
        'inputOption.activeBorder': '#0288d1',
        'inputOption.activeBackground': '#0288d130',
        'inputValidation.infoBackground': '#e1f5fe',
        'inputValidation.infoBorder': '#0288d1',
        'inputValidation.warningBackground': '#fff8e1',
        'inputValidation.warningBorder': '#ffa000',
        'inputValidation.errorBackground': '#ffebee',
        'inputValidation.errorBorder': '#d32f2f',

        'dropdown.background': '#ffffff',
        'dropdown.foreground': '#2c3e50',
        'dropdown.border': '#ccd3d9',

        'badge.background': '#0288d1',
        'badge.foreground': '#ffffff',

        'progressBar.background': '#0288d1',

        'panel.background': '#ebf1f5',
        'panel.border': '#ccd3d9',
        'panelTitle.activeForeground': '#2c3e50',
        'panelTitle.activeBorder': '#0288d1',
        'panelTitle.inactiveForeground': '#6c757d',

        'terminal.background': '#ffffff',
        'terminal.foreground': '#2c3e50',
        'terminal.border': '#ccd3d9',
        'terminal.selectionBackground': '#add6ff66',

        'tab.activeBackground': '#ffffff',
        'tab.activeForeground': '#2c3e50',
        'tab.activeBorder': '#0288d1',
        'tab.activeBorderTop': '#0288d1',
        'tab.inactiveBackground': '#e1e8ed',
        'tab.inactiveForeground': '#6c757d',
        'tab.hoverBackground': '#e1e8ed',
        'tab.hoverForeground': '#2c3e50',
        'tab.border': '#ccd3d9',
        'tab.unfocusedActiveBorder': '#ccd3d9',
        'tab.unfocusedActiveBorderTop': '#ccd3d9',

        'editor.background': '#ffffff',
        'editor.foreground': '#2c3e50',
        'editorLineNumber.foreground': '#6e7681',
        'editorLineNumber.activeForeground': '#24292f',
        'editor.selectionBackground': '#add6ff',
        'editor.selectionHighlightBackground': '#add6ff66',
        'editor.wordHighlightBackground': '#d4d4d480',
        'editor.wordHighlightStrongBackground': '#add6ff80',
        'editor.findMatchBackground': '#a8ac94',
        'editor.findMatchHighlightBackground': '#ea5c0030',
        'editor.findRangeHighlightBackground': '#d4d4d440',
        'editor.hoverHighlightBackground': '#add6ff40',
        'editorWidget.background': '#ebf1f5',
        'editorWidget.foreground': '#2c3e50',
        'editorWidget.border': '#ccd3d9',
        'editorWidget.resizeBorder': '#0288d1',

        'breadcrumb.background': '#ffffff',
        'breadcrumb.foreground': '#6c757d',
        'breadcrumb.focusForeground': '#2c3e50',
        'breadcrumb.activeSelectionForeground': '#2c3e50',
        'breadcrumbPicker.background': '#ebf1f5',

        'pickerGroup.foreground': '#0288d1',
        'pickerGroup.border': '#ccd3d9',
        'quickInput.background': '#ebf1f5',
        'quickInput.foreground': '#2c3e50',
        'quickInputList.focusBackground': '#e1e4e8',
        'quickInputList.focusForeground': '#2c3e50',

        'notificationCenter.border': '#ccd3d9',
        'notificationCenterHeader.foreground': '#2c3e50',
        'notificationCenterHeader.background': '#ebf1f5',
        'notificationToast.border': '#ccd3d9',
        'notifications.foreground': '#2c3e50',
        'notifications.background': '#ebf1f5',
        'notifications.border': '#ccd3d9',
        'notificationLink.foreground': '#0288d1',

        'settings.headerForeground': '#2c3e50',
        'settings.modifiedItemIndicator': '#90a4ae',
        'settings.dropdownBackground': '#ffffff',
        'settings.dropdownForeground': '#2c3e50',
        'settings.dropdownBorder': '#ccd3d9',
        'settings.checkboxBackground': '#ffffff',
        'settings.checkboxForeground': '#2c3e50',
        'settings.checkboxBorder': '#ccd3d9',
        'settings.textInputBackground': '#ffffff',
        'settings.textInputForeground': '#2c3e50',
        'settings.textInputBorder': '#ccd3d9',
        'settings.numberInputBackground': '#ffffff',
        'settings.numberInputForeground': '#2c3e50',
        'settings.numberInputBorder': '#ccd3d9',

        'scrollbar.shadow': '#ccd3d9',
        'scrollbarSlider.background': '#6c757d30',
        'scrollbarSlider.hoverBackground': '#6c757d50',
        'scrollbarSlider.activeBackground': '#6c757d70',

        'keybindingLabel.background': '#e4e4e4',
        'keybindingLabel.foreground': '#2c3e50',
        'keybindingLabel.border': '#ccd3d9',
        'keybindingLabel.bottomBorder': '#ccd3d9',
    },
    tokenColors: [],
    semanticHighlighting: true
};
