// *****************************************************************************
// Copyright (C) 2024 NukeHub and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0
// *****************************************************************************

/**
 * OpenMC Health Check Service
 *
 * Provides comprehensive health checks for OpenMC setup by combining
 * nuke-core infrastructure validation with OpenMC-specific checks such as
 * cross-sections library paths and depletion chain files.
 *
 * @see {@link OpenMCEnvironmentService} for environment management
 * @see {@link getOpenMCHealthPackages} for the package metadata driving checks
 * @module openmc-studio/browser
 */

import { injectable, inject } from '@theia/core/shared/inversify';
import { NukeCoreService } from 'nuke-core/lib/common';
import { getOpenMCHealthPackages } from './openmc-package-metadata';

/** A single issue discovered during a health check. */
export interface HealthCheckIssue {
    /** Severity level of the issue. */
    severity: 'error' | 'warning' | 'info';
    /** Category the issue belongs to. */
    category: 'environment' | 'openmc' | 'cross-sections' | 'chain-file' | 'mpi' | 'dagmc';
    /** Human-readable description of the issue. */
    message: string;
    /** Optional suggestion for how the user can resolve the issue. */
    suggestion?: string;
    /** Whether the issue can be resolved automatically (e.g. via package install). */
    autoFixable?: boolean;
}

/** Result of an individual health check item. */
export interface HealthCheckItem {
    /** Category the check belongs to. */
    category: HealthCheckIssue['category'];
    /** Display name of the check. */
    name: string;
    /** Whether the check passed. */
    passed: boolean;
    /** Human-readable message describing the check result. */
    message: string;
    /** Severity if the check did not pass. */
    severity?: 'error' | 'warning' | 'info';
    /** Optional suggestion for resolving a failed check. */
    suggestion?: string;
}

/** Aggregated result of a complete health check run. */
export interface HealthCheckResult {
    /** `true` if there are no errors and no warnings. */
    healthy: boolean;
    /** `true` if there are no errors (warnings and info are allowed). */
    ready: boolean;
    /** Flat list of all issues found across all checks. */
    issues: HealthCheckIssue[];
    /** Detailed list of every individual check performed. */
    checks: HealthCheckItem[];
    /** Summary counts by severity. */
    summary: {
        /** Number of error-level issues. */
        errors: number;
        /** Number of warning-level issues. */
        warnings: number;
        /** Number of info-level issues. */
        info: number;
    };
    /** Information about the active Python environment, if available. */
    environment?: {
        /** Environment display name. */
        name: string;
        /** Detected OpenMC version string. */
        version?: string;
        /** Absolute path to the Python executable. */
        pythonCommand: string;
    };
}

@injectable()
export class OpenMCHealthService {

    @inject(NukeCoreService)
    protected readonly nukeCore: NukeCoreService;

    /**
     * Run a comprehensive health check for OpenMC.
     * Combines nuke-core package health checks with OpenMC-specific validations
     * (cross-sections library, depletion chain file).
     * @returns A {@link HealthCheckResult} containing all issues, checks, and summary counts.
     */
    async runHealthCheck(): Promise<HealthCheckResult> {
        const issues: HealthCheckIssue[] = [];
        const checks: HealthCheckItem[] = [];

        // 1. Core infrastructure + ALL packages via nuke-core (rich suggestions generated by nuke-core)
        const coreResult = await this.nukeCore.healthCheck(getOpenMCHealthPackages());

        const env = await this.nukeCore.getSelectedEnvironment();

        for (const coreCheck of coreResult.checks) {
            const category = this.inferCategory(coreCheck.name);
            checks.push({
                category,
                name: coreCheck.name,
                passed: coreCheck.passed,
                message: coreCheck.message,
                severity: coreCheck.severity,
                suggestion: coreCheck.suggestion
            });
            if (!coreCheck.passed && coreCheck.severity) {
                issues.push({
                    severity: coreCheck.severity,
                    category,
                    message: coreCheck.message,
                    suggestion: coreCheck.suggestion,
                    autoFixable: coreCheck.severity === 'error'
                });
            }
        }

        // Can't proceed without a working Python environment
        const pythonFailed = coreResult.checks.some(
            c => c.name === 'Configured Python Environment' && !c.passed
        );
        if (pythonFailed || !env) {
            return this.createResult(issues, checks, undefined);
        }

        // 2. Cross-sections
        const xs = this.checkCrossSections();
        issues.push(...xs.issues);
        checks.push(...xs.checks);

        // 3. Chain file
        const chain = this.checkChainFile();
        issues.push(...chain.issues);
        checks.push(...chain.checks);

        // Extract OpenMC version from core health check
        const openmcCheck = coreResult.checks.find(
            c => c.name === 'Package: openmc' && c.passed
        );
        let version: string | undefined;
        if (openmcCheck) {
            const match = openmcCheck.message.match(/openmc\s+([\d.]+)/i);
            version = match ? match[1] : undefined;
        }

        return this.createResult(issues, checks, {
            name: env.name,
            version,
            pythonCommand: env.pythonPath
        });
    }

    /**
     * Quick check if OpenMC is ready to run.
     * Equivalent to calling {@link runHealthCheck} and checking `ready`.
     * @returns `true` if no errors were found and a Python environment is available.
     */
    async isReady(): Promise<boolean> {
        const result = await this.runHealthCheck();
        return result.ready;
    }

    /**
     * Get a human-readable status summary from a health check result.
     * @param result The {@link HealthCheckResult} to summarize.
     * @returns A short status string, e.g. "OpenMC ready (env 0.14.0)" or the first error message.
     */
    getStatusMessage(result: HealthCheckResult): string {
        if (result.ready) {
            return `OpenMC ready (${result.environment?.name}${result.environment?.version ? ' ' + result.environment.version : ''})`;
        }
        const errors = result.issues.filter(i => i.severity === 'error');
        if (errors.length > 0) {
            return errors[0].message;
        }
        return 'OpenMC not configured';
    }

    // -------------------------------------------------------------------------
    // Individual Check Methods
    // -------------------------------------------------------------------------

    /**
     * Validate the cross-sections library configuration.
     * Checks whether `OPENMC_CROSS_SECTIONS` is set via nuke-core settings.
     * @returns Issues and checks arrays for cross-sections validation.
     */
    private checkCrossSections(): { issues: HealthCheckIssue[]; checks: HealthCheckItem[] } {
        const issues: HealthCheckIssue[] = [];
        const checks: HealthCheckItem[] = [];
        const xsPath = this.nukeCore.getCrossSectionsPath();

        if (!xsPath) {
            const issue: HealthCheckIssue = {
                severity: 'warning',
                category: 'cross-sections',
                message: 'Cross-sections path not set',
                suggestion: 'Set OPENMC_CROSS_SECTIONS environment variable or configure in Settings → Nuke Utils',
                autoFixable: false
            };
            issues.push(issue);
            checks.push({
                category: 'cross-sections',
                name: 'Cross-sections Library',
                passed: false,
                message: issue.message,
                severity: 'warning',
                suggestion: issue.suggestion
            });
        } else {
            checks.push({
                category: 'cross-sections',
                name: 'Cross-sections Library',
                passed: true,
                message: `Path set: ${xsPath}`
            });
        }

        return { issues, checks };
    }

    /**
     * Validate the depletion chain file configuration.
     * Checks whether `OPENMC_CHAIN_FILE` is set via nuke-core settings.
     * @returns Issues and checks arrays for chain file validation.
     */
    private checkChainFile(): { issues: HealthCheckIssue[]; checks: HealthCheckItem[] } {
        const issues: HealthCheckIssue[] = [];
        const checks: HealthCheckItem[] = [];
        const chainPath = this.nukeCore.getChainFilePath();

        if (!chainPath) {
            const issue: HealthCheckIssue = {
                severity: 'info',
                category: 'chain-file',
                message: 'Chain file not set (only needed for depletion)',
                suggestion: 'Set OPENMC_CHAIN_FILE to enable depletion calculations'
            };
            issues.push(issue);
            checks.push({
                category: 'chain-file',
                name: 'Depletion Chain File',
                passed: false,
                message: issue.message,
                severity: 'info',
                suggestion: issue.suggestion
            });
        } else {
            checks.push({
                category: 'chain-file',
                name: 'Depletion Chain File',
                passed: true,
                message: `Path set: ${chainPath}`
            });
        }

        return { issues, checks };
    }

    // -------------------------------------------------------------------------
    // Helper Methods
    // -------------------------------------------------------------------------

    /**
     * Infer the health check category from a nuke-core check name.
     * @param name The check name produced by nuke-core (e.g. "Package: openmc", "Configured Python Environment").
     * @returns The inferred {@link HealthCheckItem.category} value.
     */
    private inferCategory(name: string): HealthCheckItem['category'] {
        if (name.includes('Python') || name === 'Conda/Mamba' || name === 'UV') {
            return 'environment';
        }
        if (name.includes('mpi4py')) {
            return 'mpi';
        }
        if (name.includes('pydagmc') || name.includes('pymoab') || name.includes('moab')) {
            return 'dagmc';
        }
        return 'openmc';
    }

    /**
     * Assemble the final {@link HealthCheckResult} from collected issues and checks.
     * @param issues All issues discovered during the health check.
     * @param checks All individual check items performed.
     * @param environment Optional environment metadata if a valid Python env was found.
     * @returns The fully populated {@link HealthCheckResult}.
     */
    private createResult(
        issues: HealthCheckIssue[],
        checks: HealthCheckItem[],
        environment?: { name: string; version?: string; pythonCommand: string }
    ): HealthCheckResult {
        const errors = issues.filter(i => i.severity === 'error').length;
        const warnings = issues.filter(i => i.severity === 'warning').length;
        const info = issues.filter(i => i.severity === 'info').length;

        // Ready if no errors and environment is available
        const ready = errors === 0 && !!environment;

        return {
            healthy: ready && warnings === 0,
            ready,
            issues,
            checks,
            summary: { errors, warnings, info },
            environment
        };
    }
}
