// *****************************************************************************
// Copyright (C) 2024 NukeHub and others.
//
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v. 2.0 which is available at
// http://www.eclipse.org/legal/epl-2.0.
//
// This Source Code may also be made available under the following Secondary
// Licenses when the conditions for such availability set forth in the Eclipse
// Public License v. 2.0 are satisfied: GNU General Public License, version 2
// with the GNU Classpath Exception which is available at
// https://www.gnu.org/software/classpath/license.html.
//
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0
// *****************************************************************************

/**
 * OpenMC Health Check Service
 *
 * Provides comprehensive health checks for OpenMC setup.
 *
 * @module openmc-studio/browser
 */

import { injectable, inject } from '@theia/core/shared/inversify';
import { NukeCoreService } from 'nuke-core/lib/common';
import { getOpenMCHealthPackages } from './openmc-package-metadata';

export interface HealthCheckIssue {
    severity: 'error' | 'warning' | 'info';
    category: 'environment' | 'openmc' | 'cross-sections' | 'chain-file' | 'mpi' | 'dagmc';
    message: string;
    suggestion?: string;
    autoFixable?: boolean;
}

export interface HealthCheckItem {
    category: HealthCheckIssue['category'];
    name: string;
    passed: boolean;
    message: string;
    severity?: 'error' | 'warning' | 'info';
    suggestion?: string;
}

export interface HealthCheckResult {
    healthy: boolean;
    ready: boolean;
    issues: HealthCheckIssue[];
    checks: HealthCheckItem[];
    summary: {
        errors: number;
        warnings: number;
        info: number;
    };
    environment?: {
        name: string;
        version?: string;
        pythonCommand: string;
    };
}

@injectable()
export class OpenMCHealthService {

    @inject(NukeCoreService)
    protected readonly nukeCore: NukeCoreService;

    /**
     * Run comprehensive health check.
     */
    async runHealthCheck(): Promise<HealthCheckResult> {
        const issues: HealthCheckIssue[] = [];
        const checks: HealthCheckItem[] = [];

        // 1. Core infrastructure + ALL packages via nuke-core (rich suggestions generated by nuke-core)
        const coreResult = await this.nukeCore.healthCheck(getOpenMCHealthPackages());

        const env = await this.nukeCore.getSelectedEnvironment();

        for (const coreCheck of coreResult.checks) {
            const category = this.inferCategory(coreCheck.name);
            checks.push({
                category,
                name: coreCheck.name,
                passed: coreCheck.passed,
                message: coreCheck.message,
                severity: coreCheck.severity,
                suggestion: coreCheck.suggestion
            });
            if (!coreCheck.passed && coreCheck.severity) {
                issues.push({
                    severity: coreCheck.severity,
                    category,
                    message: coreCheck.message,
                    suggestion: coreCheck.suggestion,
                    autoFixable: coreCheck.severity === 'error'
                });
            }
        }

        // Can't proceed without a working Python environment
        const pythonFailed = coreResult.checks.some(
            c => c.name === 'Configured Python Environment' && !c.passed
        );
        if (pythonFailed || !env) {
            return this.createResult(issues, checks, undefined);
        }

        // 2. Cross-sections
        const xs = this.checkCrossSections();
        issues.push(...xs.issues);
        checks.push(...xs.checks);

        // 3. Chain file
        const chain = this.checkChainFile();
        issues.push(...chain.issues);
        checks.push(...chain.checks);

        // Extract OpenMC version from core health check
        const openmcCheck = coreResult.checks.find(
            c => c.name === 'Package: openmc' && c.passed
        );
        let version: string | undefined;
        if (openmcCheck) {
            const match = openmcCheck.message.match(/openmc\s+([\d.]+)/i);
            version = match ? match[1] : undefined;
        }

        return this.createResult(issues, checks, {
            name: env.name,
            version,
            pythonCommand: env.pythonPath
        });
    }

    /**
     * Quick check if OpenMC is ready to run.
     */
    async isReady(): Promise<boolean> {
        const result = await this.runHealthCheck();
        return result.ready;
    }

    /**
     * Get a human-readable status summary.
     */
    getStatusMessage(result: HealthCheckResult): string {
        if (result.ready) {
            return `OpenMC ready (${result.environment?.name}${result.environment?.version ? ' ' + result.environment.version : ''})`;
        }
        const errors = result.issues.filter(i => i.severity === 'error');
        if (errors.length > 0) {
            return errors[0].message;
        }
        return 'OpenMC not configured';
    }

    // -------------------------------------------------------------------------
    // Individual Check Methods
    // -------------------------------------------------------------------------

    private checkCrossSections(): { issues: HealthCheckIssue[]; checks: HealthCheckItem[] } {
        const issues: HealthCheckIssue[] = [];
        const checks: HealthCheckItem[] = [];
        const xsPath = this.nukeCore.getCrossSectionsPath();

        if (!xsPath) {
            const issue: HealthCheckIssue = {
                severity: 'warning',
                category: 'cross-sections',
                message: 'Cross-sections path not set',
                suggestion: 'Set OPENMC_CROSS_SECTIONS environment variable or configure in Settings → Nuke Utils',
                autoFixable: false
            };
            issues.push(issue);
            checks.push({
                category: 'cross-sections',
                name: 'Cross-sections Library',
                passed: false,
                message: issue.message,
                severity: 'warning',
                suggestion: issue.suggestion
            });
        } else {
            checks.push({
                category: 'cross-sections',
                name: 'Cross-sections Library',
                passed: true,
                message: `Path set: ${xsPath}`
            });
        }

        return { issues, checks };
    }

    private checkChainFile(): { issues: HealthCheckIssue[]; checks: HealthCheckItem[] } {
        const issues: HealthCheckIssue[] = [];
        const checks: HealthCheckItem[] = [];
        const chainPath = this.nukeCore.getChainFilePath();

        if (!chainPath) {
            const issue: HealthCheckIssue = {
                severity: 'info',
                category: 'chain-file',
                message: 'Chain file not set (only needed for depletion)',
                suggestion: 'Set OPENMC_CHAIN_FILE to enable depletion calculations'
            };
            issues.push(issue);
            checks.push({
                category: 'chain-file',
                name: 'Depletion Chain File',
                passed: false,
                message: issue.message,
                severity: 'info',
                suggestion: issue.suggestion
            });
        } else {
            checks.push({
                category: 'chain-file',
                name: 'Depletion Chain File',
                passed: true,
                message: `Path set: ${chainPath}`
            });
        }

        return { issues, checks };
    }

    // -------------------------------------------------------------------------
    // Helper Methods
    // -------------------------------------------------------------------------

    private inferCategory(name: string): HealthCheckItem['category'] {
        if (name.includes('Python') || name === 'Conda/Mamba' || name === 'UV') {
            return 'environment';
        }
        if (name.includes('mpi4py')) {
            return 'mpi';
        }
        if (name.includes('pydagmc') || name.includes('pymoab') || name.includes('moab')) {
            return 'dagmc';
        }
        return 'openmc';
    }

    private createResult(
        issues: HealthCheckIssue[],
        checks: HealthCheckItem[],
        environment?: { name: string; version?: string; pythonCommand: string }
    ): HealthCheckResult {
        const errors = issues.filter(i => i.severity === 'error').length;
        const warnings = issues.filter(i => i.severity === 'warning').length;
        const info = issues.filter(i => i.severity === 'info').length;

        // Ready if no errors and environment is available
        const ready = errors === 0 && !!environment;

        return {
            healthy: ready && warnings === 0,
            ready,
            issues,
            checks,
            summary: { errors, warnings, info },
            environment
        };
    }
}
